<?php
return [
	'emailAddress' => array(
		'contact' => 'contact@quizzy.sg',
		'noreply' => 'noreply@quizzy.sg',
	),
	'user' => array(
		'securityKey' => '}&!bI^mV}EfBIcGdGP^.>SFV/s*S/AaIujmZ6Y^TM,Jo`Q=FHm"=@|TolkjWwcE&',
		'defaultFolderViewSideBar' => 3,
		'profilePictureList' => array(
			array('key' => 'C0E573wpv80EYHvkA6jL', 'value' => '/images/profile/user.png'),
			array('key' => 'GHjNWs5xk75piSk1WVtz', 'value' => '/images/profile/GHjNWs5xk75piSk1WVtz.png'),
			array('key' => 'QAlQFVHP4GEDM5P9nkA6', 'value' => '/images/profile/QAlQFVHP4GEDM5P9nkA6.png'),
			array('key' => 'P3Wvkd2wfiDhpGBklMCr', 'value' => '/images/profile/P3Wvkd2wfiDhpGBklMCr.png'),
			array('key' => '4L4L43bSKL3QBB678hWA', 'value' => '/images/profile/4L4L43bSKL3QBB678hWA.png'),
			array('key' => 'tKN9laQ1xe49V27JRTQ7', 'value' => '/images/profile/tKN9laQ1xe49V27JRTQ7.png'),
			array('key' => 'shUEmvDbTBfX1epAfu2B', 'value' => '/images/profile/shUEmvDbTBfX1epAfu2B.png'),
			array('key' => 'NsW1t73wpvlqRzUjX9y9', 'value' => '/images/profile/NsW1t73wpvlqRzUjX9y9.png'),
			array('key' => 'pfQAxmy4J40YIBsiiNtI', 'value' => '/images/profile/pfQAxmy4J40YIBsiiNtI.png'),
			array('key' => 'qMTaKRRlazGDiKQsTvSm', 'value' => '/images/profile/qMTaKRRlazGDiKQsTvSm.png'),
			array('key' => 'RXdajBGPm2fYwKQPnIWq', 'value' => '/images/profile/RXdajBGPm2fYwKQPnIWq.png'),
			array('key' => 'nWfuEKhMeIHQL2LnxBth', 'value' => '/images/profile/nWfuEKhMeIHQL2LnxBth.png'),
			array('key' => 'zQh0gGt5NUNWStNM34gw', 'value' => '/images/profile/zQh0gGt5NUNWStNM34gw.png'),
			array('key' => '9ATDQNBi873S4qQiysXR', 'value' => '/images/profile/9ATDQNBi873S4qQiysXR.png'),
			array('key' => '5mJwchqHAlT5uErQdXu6', 'value' => '/images/profile/5mJwchqHAlT5uErQdXu6.png'),
			array('key' => 'F4wi6YvFEEHvkAkjdi10', 'value' => '/images/profile/F4wi6YvFEEHvkAkjdi10.png'),
			array('key' => '7ksGfj1Oi7QITAclxAlM', 'value' => '/images/profile/7ksGfj1Oi7QITAclxAlM.png'),
			array('key' => 'Za4NNilUAJhDUS5PWrZp', 'value' => '/images/profile/Za4NNilUAJhDUS5PWrZp.png'),
			array('key' => 'ApOYNu0Q6RpsYpeXFOGX', 'value' => '/images/profile/ApOYNu0Q6RpsYpeXFOGX.png'),
			array('key' => '8dWVk3cWi7SyU5DU5Qsp', 'value' => '/images/profile/8dWVk3cWi7SyU5DU5Qsp.png'),
			array('key' => 'tPZnBITREBqq2FNbPmGF', 'value' => '/images/profile/tPZnBITREBqq2FNbPmGF.png'),
			array('key' => 'VmbAqsC0E580EY6jLMbj', 'value' => '/images/profile/VmbAqsC0E580EY6jLMbj.png'),
		),
		'profilePictureAllowedExtension' => array(
			'image/jpeg',
			'image/png',
		),
		'forbidUsername' => array(
			'about-us',
			'how',
			'news',
			'faq',
			'contact-us',
			'privacy',
			'login',
			'logout',
			'register',
			'dashboard',
			'settings',
		),
	),
	'month' => array(
		'01' => 'January',
		'02' => 'February',
		'03' => 'March',
		'04' => 'April',
		'05' => 'May',
		'06' => 'June',
		'07' => 'July',
		'08' => 'August',
		'09' => 'September',
		'10' => 'October',
		'11' => 'November',
		'12' => 'December',
	), 
	'year' => array(
		'registration' => array(
		),
	),
	'dateFormat' => array(
		'registration' => 'Y-m-d H:i:s',
		'set' => 'Y-m-d H:i:s',
		'standard' => 'Y-m-d H:i:s',
		'display' => 'M d, Y',
		'reporting' => 'd M Y',
	),
	'set' => array(
		'createDefaultNumber' => 3,
		'limitPerSetTermsDefinition' => 3,
		'maxLeaderboardDisplay' => 5,
	),
];